name: $(Build.SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
variables:
  Parameters.RestoreBuildProjects: "**/*.csproj"
  Parameters.TestProjects: "**/*[Tt]ests/*.csproj"
  BuildConfiguration: "Release"
  BuildPlatform: "any cpu"
  
trigger:
  batch: true
  branches:
    include: [ "*" ]
  paths:
    exclude: [ 
      "README.md",
      ".vs",
      ".vscode",
      ".git*",
      "config.toml"
    ]

jobs:
  - job: build
    displayName: "build"
    pool:
      vmImage: "ubuntu-16.04"
    workspace:
      clean: all
    timeoutInMinutes: 120
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '$(Parameters.RestoreBuildProjects)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '$(Parameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '$(Parameters.TestProjects)'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: '$(Parameters.RestoreBuildProjects)'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: ScreenShooter

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(build.artifactstagingdirectory)/ScreenShooter'
        contents: '**' 
        targetFolder: 'publish'
        cleanTargetFolder: true
        overWrite: true

    - task: Docker@1
      displayName: 'Build image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub: Jamesits'
        imageName: 'jamesits/screenshooter'
        arguments: '--build-arg BUILD_OUTPUT_DIR=publish'
        includeSourceTags: true
        includeLatestTag: true

    - task: Docker@1
      displayName: 'Push image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub: Jamesits'
        command: 'Push an image'
        imageName: 'jamesits/screenshooter'

